packages:
  - packages/contracts
  - frontend
  - server

allowBuilds:
  browser-tabs-lock: true
  esbuild: true
  msw: true
  unrs-resolver: true

minimumReleaseAgeExclude:
  - msw-storybook-addon@3.0.3

onlyBuiltDependencies:
  - browser-tabs-lock
  - esbuild
  - msw
  - unrs-resolver
